<?php

use Lib\Ingredient;

?>

<h2>Items</h2>

<div class="row">
    <div class="col mb-2 text-right">
        <a href="<?= $this->url('ingredient', ['action' => 'create']); ?>" class="btn btn-info">New</a>
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <div class="table-responsive">
            <table class="table" id="itemsTable">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Unit</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                <?php
                /** @var Ingredient $ingredient */
                foreach ($this->ingredients as $ingredient) : ?>
                    <tr>
                        <td><?= $ingredient->getName(); ?></td>
                        <td><?= $ingredient->getUnit(); ?></td>

                        <td nowrap="whitespace">

                            <!-- view button -->
                            <a class="btn btn-info btn-sm"
                               href="<?= $this->url('ingredient', [
                                   'action' => 'view',
                                   'id' => $ingredient->getId()
                               ]); ?>">
                                View
                            </a>

                            <!-- Edit button -->
                            <a class="btn btn-primary btn-sm"
                               href="<?= $this->url('ingredient', [
                                   'action' => 'edit',
                                   'id' => $ingredient->getId()
                               ]); ?>">
                                Edit
                            </a>

                            <!-- delete button -->
                            <a class="btn btn-danger btn-sm"
                               href="<?= $this->url('ingredient', [
                                   'action' => 'delete',
                                   'id' => $ingredient->getId()
                               ]); ?>">
                                Delete
                            </a>

                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready( function () {
        $('#itemsTable').DataTable();
    } );
</script>