
<div class="row">
    <div class="col">
        <h1><?= $this->ingredient->getName(); ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-lg">

        <div class="card mt-3">
            <div class="card-header">
                Part of Recipes
            </div>
            <div class="table-responsive">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th> <!-- link to recipe -->
                        <th>Serves</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>

            </div>
        </div>
    </div>


</div>
