version: '3'

services:

  app:
    build: .
    ports:
      - 40040:80
    volumes:
      - .:/var/www
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 33068:3306
    command: --sql_mode=""
    environment:
      MYSQL_DATABASE: fp
      MYSQL_USER: admin
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: password