<?php

use Lib\ShoppingList;

?>

<h2>Shopping Lists</h2>

<div class="row">
    <div class="col mb-2 text-right">
        <a href="<?= $this->url('list', ['action' => 'create']); ?>" class="btn btn-info">New</a>
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>#</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                    <?php
                    /** @var ShoppingList $list */
                    foreach ($this->lists as $list) : ?>
                        <tr>
                            <td><?= $list->getName(); ?></td>
                            <td><?= $list->getListRecipes()->count(); ?></td>
                            <td nowrap="whitespace">

                                <!-- view button -->
                                <a class="btn btn-info btn-sm"
                                   href="<?= $this->url('list', [
                                       'action' => 'view',
                                       'id' => $list->getId()
                                   ]); ?>">
                                    View
                                </a>

                                <!-- Edit button -->
                                <a class="btn btn-primary btn-sm"
                                   href="<?= $this->url('list-recipe', [
                                       'list_id' => $list->getId()
                                   ]); ?>">
                                    Manage Recipes
                                </a>

                                <!-- Meal Planner button -->
                                <a class="btn btn-success btn-sm"
                                   href="<?= $this->url('planner', [
                                       'list_id' => $list->getId()
                                   ]); ?>">
                                    Meal Planner
                                </a>

                                <!-- delete button -->
                                <a class="btn btn-danger btn-sm"
                                   href="<?= $this->url('list', [
                                       'action' => 'delete',
                                       'id' => $list->getId()
                                   ]); ?>">
                                    Delete
                                </a>

                            </td>
                        </tr>
                    <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>