<?php

use Lib\ShoppingListItem;

?>

<div class="row">
    <div class="col">
        <h1>
            <?= $this->list->getName(); ?>

            <!-- Meal Planner button -->
            <a class="btn btn-success btn-sm"
               href="<?= $this->url('planner', [
                   'list_id' => $this->list->getId()
               ]); ?>">
                Meal Planner
            </a>
        </h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <div class="card mt-3">
            <div class="card-header">
                Add Single Item
            </div>
            <div class="card-body">

                <form action="<?= $this->url('list', ['action' => 'addItem', 'id' => $list->getId()]); ?>"
                      method="POST">

                    <div class="form-group">
                        <label for="item_id">Item</label>
                        <select class="form-control select2" name="item_id" id="item_id">
                            <?php foreach ($this->items as $item) : ?>
                                <option value="<?= $item->getId(); ?>">
                                    <?= $item->getName(); ?> (<?= $item->getUnit(); ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="text" class="form-control" name="quantity" id="quantity" />
                    </div>

                    <button type="submit" class="btn btn-primary float-right">
                        Add to List
                    </button>
                </form>

            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="card mt-3">
            <div class="card-header">
                Full Shopping List
            </div>
            <div class="table-responsive" style="max-height: 600px; overflow: auto;">

                <?= $this->partial('shopping/list', [
                    'items' => $this->shoppingList,
                    'list' => $list
                ]); ?>


            </div>
        </div>
    </div>
</div>
