
<div class="row">
    <div class="col">
        <h1><?= $this->list->getName(); ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <div class="card mt-3">
            <div class="card-header">
                Recipes in List
            </div>
            <div class="table-responsive">

                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Serves</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>

            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="card mt-3">
            <div class="card-header">
                Full Shopping List
            </div>
            <div class="card-body">

            </div>
        </div>
    </div>
</div>
