<?php

use Lib\ShoppingListItem;

?>

<div class="row">
    <div class="col">
        <h1><?= $this->list->getName(); ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-8">

        <div class="card mt-3">
            <div class="card-header">
                Add Single Item
            </div>
            <div class="card-body">



            </div>
        </div>
    </div>


    <div class="col-md-4">
        <div class="card mt-3">
            <div class="card-header">
                Full Shopping List
            </div>
            <div class="table-responsive" style="max-height: 600px; overflow: auto;">

                <?= $this->partial('shopping/list', [
                    'items' => $this->shoppingList,
                    'list' => $list
                ]); ?>


            </div>
        </div>
    </div>
</div>
