<?php

use Lib\ShoppingList;

/** @var ShoppingList $list */
$list = $this->list;

?>

<h2><?= $this->list->getName(); ?> / Recipes</h2>

<div class="row">
    <div class="col-md-8">

        <div class="card mt-3">
            <div class="card-header">
                Add to List
            </div>
            <div class="card-body">

                <form method="POST" action="<?= $this->url('list-recipe', [
                    'action' => 'add',
                    'list_id' => $this->list->getId()
                ]); ?>">

                    <div class="form-group">
                        <label for="recipe_id">Select Recipe</label>
                        <select class="form-control" name="recipe_id" id="recipe_id">
                            <?php foreach ($this->recipes as $recipe) : ?>
                                <option value="<?= $recipe->getId(); ?>">
                                    <?= $recipe->getName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="servings">Number of Servings</label>
                        <input type="number" class="form-control" name="servings" id="servings" />
                    </div>

                    <button type="submit" class="btn btn-success float-right">
                        Add Recipe
                    </button>

                </form>

            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                Recipes in List
            </div>
            <div class="table-responsive" style="max-height: 330px; overflow: auto;">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Serves</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($list->getListRecipesJoinRecipe() as $recipe) : ?>
                        <tr>
                            <td><?= $recipe->getRecipe()->getName(); ?></td>
                            <td><?= $recipe->getServes(); ?></td>
                            <td>

                                <!-- Remove button -->
                                <a class="btn btn-sm btn-danger" href="<?= $this->url('list-recipe', [
                                    'list_id' => $list->getId(),
                                    'action' => 'remove',
                                    'id' => $recipe->getId()
                                ]); ?>">
                                    Remove
                                </a>

                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>

    <div class="col-md-4">

        <div class="card mt-3">
            <div class="card-header">
                Shopping List
            </div>
            <div class="table-responsive" style="max-height: 650px; overflow: auto;">


                <table class="table table-condensed">
                    <tbody>
                        <?php foreach ($list->getFullItemList() as $item) : ?>
                            <tr>
                                <td><?= $item['Name']; ?></td>
                                <td><?= $item['total']; ?> <?= $item['Unit']; ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>

</div>

