<?php

use Lib\DayPlanRecipe;

?>

<div class="row">
    <div class="col-lg">
        <h5><?= $this->title; ?></h5>

        <div class="table-responsive">

            <table class="table table-sm table-striped table-bordered">
            <?php
            /** @var DayPlanRecipe $recipe */
            foreach ($this->recipes as $recipe) : ?>

                <tr>
                    <td style="width: 64%;">
                        <a href="<?= $this->url('recipe', [
                            'id' => $recipe->getRecipeId(),
                            'action' => 'view'
                        ]); ?>">
                            <?= $recipe->getRecipe()->getName(); ?>
                        </a>
                    </td>

                    <td style="width: 12%;">
                        <?php if ($recipe->getRecipe()->getCalories()) : ?>
                            <?= $recipe->getRecipe()->getCalories(); ?>
                        <?php endif; ?>
                    </td>

                    <td style="width: 12%;">
                        x <?= $recipe->getServers(); ?>
                    </td>
                    <td style="width: 12%;">
                        <!-- Delete button -->
                        <a class="btn btn-sm btn-danger" href="<?= $this->url('planner', [
                            'list_id' => $this->listId,
                            'action' => 'removeRecipe',
                            'id' => $recipe->getId()
                        ]); ?>">
                            X
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>