<?php

use Lib\Item;

?>

<h2>Items</h2>

<div class="row">
    <div class="col mb-2 text-right">
        <a href="<?= $this->url('item', ['action' => 'create']); ?>" class="btn btn-info">New</a>
    </div>
</div>

<div class="row">
    <div class="col-lg">
        <div class="table-responsive">
            <table class="table" id="itemsTable">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Unit</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                <?php
                /** @var Item $item */
                foreach ($this->items as $item) : ?>
                    <tr>
                        <td><?= $item->getName(); ?></td>
                        <td><?= $item->getUnit(); ?></td>

                        <td nowrap="whitespace">

                            <!-- view button -->
                            <a class="btn btn-info btn-sm"
                               href="<?= $this->url('item', [
                                   'action' => 'view',
                                   'id' => $item->getId()
                               ]); ?>">
                                View
                            </a>

                            <!-- Edit button -->
                            <a class="btn btn-primary btn-sm"
                               href="<?= $this->url('item', [
                                   'action' => 'edit',
                                   'id' => $item->getId()
                               ]); ?>">
                                Edit
                            </a>

                            <!-- delete button -->
                            <a class="btn btn-danger btn-sm"
                               href="<?= $this->url('item', [
                                   'action' => 'delete',
                                   'id' => $item->getId()
                               ]); ?>">
                                Delete
                            </a>

                        </td>
                    </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready( function () {
        $('#itemsTable').DataTable();
    } );
</script>