<?php

use Lib\Item;

/** @var Item $item */
$item = $this->item;
?>

<div class="row">
    <div class="col">
        <h1><?= $item->getName(); ?> (<?= $item->getUnit(); ?>)</h1>
    </div>
</div>

<div class="row">
    <div class="col-lg">

        <div class="card mt-3">
            <div class="card-header">
                Used In
            </div>
            <div class="table-responsive">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Recipe Name</th> <!-- link to recipe -->
                        <th>Quantity</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($item->getRecipeItemsJoinRecipe() as $recipeItem) : ?>
                            <tr>
                                <td><?= $recipeItem->getRecipe()->getName(); ?></td>
                                <td><?= $recipeItem->getQuantity(); ?> <?= $item->getUnit(); ?></td>
                                <td>
                                    <!-- go to recipe button -->
                                    <a href="<?= $this->url('recipe', [
                                        'action' => 'view',
                                        'id' => $recipeItem->getRecipeId()
                                    ]); ?>" class="btn btn-success">
                                        Go To Recipe
                                    </a>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>
    </div>


</div>
