<?php

use Lib\Ingredient;
use Lib\Recipe;

/** @var Recipe $recipe */
$recipe = $this->recipe;

?>

<h2><?= $recipe->getName(); ?> / Ingredients</h2>

<div class="row">
    <div class="col-md">

        <div class="card mt-3">
            <div class="card-header">
                Ingredients in Recipe
            </div>
            <div class="table-responsive">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($recipe->getRecipeIngredientsJoinIngredient() as $ingredient) : ?>
                        <tr>
                            <td><?= $ingredient->getIngredient()->getName(); ?></td>
                            <td><?= $ingredient->getQuantity(); ?></td>
                            <td><?= $ingredient->getIngredient()->getUnit(); ?></td>
                            <td>
                                <a class="btn btn-sm btn-danger" href="<?= $this->url('recipe-ingredient', [
                                    'action' => 'remove',
                                    'recipe_id' => $recipe->getId(),
                                    'id' => $ingredient->getId()
                                ]); ?>">
                                    Remove
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>

    <div class="col-md">
        <div class="card mt-3">
            <div class="card-header">
                Add to Recipe
            </div>
            <div class="card-body">

                <form method="POST" action="<?= $this->url('recipe-ingredient', [
                    'action' => 'add',
                    'recipe_id' => $recipe->getId()
                ]); ?>">

                    <div class="form-group">
                        <label for="ingredient_id">Select Ingredient</label>
                        <select class="form-control" name="ingredient_id" id="ingredient_id">
                            <?php
                            /** @var Ingredient $ingredient */
                            foreach ($this->ingredients as $ingredient) : ?>
                                <option value="<?= $ingredient->getId(); ?>">
                                    <?= $ingredient->getName(); ?> (<?= $ingredient->getUnit(); ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="number" class="form-control" name="quantity" id="quantity" />
                        <small>
                            This should be the quantity for <strong>one single serving.</strong>
                        </small>
                    </div>

                    <button type="submit" class="btn btn-success float-right">
                        Add Ingredient
                    </button>

                </form>

            </div>
        </div>
    </div>
</div>

