<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Food Planner')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

            // Boostrap
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))

            // Select2
            ->prependStylesheet('//cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css')

            // Datatables
            ->prependStylesheet('//cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css')

            // FA Icons
            ->prependStylesheet($this->basePath('fontawesome/css/all.css'))

            // Custom Styles
            ->prependStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()

            // Select2
            ->prependFile('//cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js')

            // Datatables
            ->prependFile('//cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js')
            ->prependFile('//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js')

            // Bootstrap & jquery
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js'))
        ?>

        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Food Planner
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('list') ?>">Lists</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('recipe') ?>">Recipes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('item') ?>">Items</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">

            <?= html_entity_decode($this->flashMessenger()->render('error', ['alert', 'alert-danger'])); ?>
            <?= html_entity_decode($this->flashMessenger()->render('success', ['alert', 'alert-success'])); ?>
            <?= html_entity_decode($this->flashMessenger()->render('info', ['alert', 'alert-info'])); ?>


            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> Food Planner</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>

        <script type="text/javascript">
            $(document).ready(function() {
                $('.select2').select2();
            });
        </script>

    </body>
</html>
