<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Food Planner')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Food Planner
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('list') ?>">Lists</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('recipe') ?>">Recipes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->url('ingredient') ?>">Ingredients</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">

            <?= html_entity_decode($this->flashMessenger()->render('error', ['alert', 'alert-danger'])); ?>
            <?= html_entity_decode($this->flashMessenger()->render('success', ['alert', 'alert-success'])); ?>
            <?= html_entity_decode($this->flashMessenger()->render('info', ['alert', 'alert-info'])); ?>


            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> Food Planner</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
