<?php

use Lib\Item;
use Lib\Recipe;

/** @var Recipe $recipe */
$recipe = $this->recipe;

?>

<h2>
    <?= $recipe->getName(); ?>
    <a class="btn btn-success btn-sm" href="<?= $this->url('recipe', [
        'action' => 'edit',
        'id' => $recipe->getId()
    ]); ?>">
        Edit
    </a>
    / Items
</h2>

<div class="row">
    <div class="col-md">

        <div class="card mt-3">
            <div class="card-header">
                Items in Recipe
            </div>
            <div class="table-responsive">

                <table class="table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($recipe->getRecipeItemsJoinItem() as $item) : ?>
                        <tr>
                            <td><?= $item->getItem()->getName(); ?></td>
                            <td><?= $item->getQuantity(); ?></td>
                            <td><?= $item->getItem()->getUnit(); ?></td>
                            <td>
                                <a class="btn btn-sm btn-danger" href="<?= $this->url('recipe-item', [
                                    'action' => 'remove',
                                    'recipe_id' => $recipe->getId(),
                                    'id' => $item->getId()
                                ]); ?>">
                                    Remove
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>

            </div>
        </div>

    </div>

    <div class="col-md">
        <div class="card mt-3">
            <div class="card-header">
                Add to Recipe
            </div>
            <div class="card-body">

                <form method="POST" action="<?= $this->url('recipe-item', [
                    'action' => 'add',
                    'recipe_id' => $recipe->getId()
                ]); ?>">

                    <div class="form-group">
                        <label for="item_id">Select Item</label>
                        <select class="form-control select2" name="item_id" id="item_id">
                            <?php
                            /** @var Item $item */
                            foreach ($this->items as $item) : ?>
                                <option value="<?= $item->getId(); ?>">
                                    <?= $item->getName(); ?> (<?= $item->getUnit(); ?>)
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="quantity">Quantity</label>
                        <input type="number" step="0.01" class="form-control" name="quantity" id="quantity" />
                        <small>
                            This should be the quantity for <strong>one single serving.</strong>
                        </small>
                    </div>

                    <button type="submit" class="btn btn-success float-right">
                        Add Item
                    </button>

                </form>

            </div>
        </div>
    </div>
</div>

