<?php

use Lib\DayPlan;

$counter = 1;
?>

<h2>Meal Planner for <?= $this->list->getName(); ?></h2>

<a class="btn btn-success" href="<?= $this->url('planner', [
    'list_id' => $this->list->getId(),
    'action' => 'add'
]); ?>">
    + Add a Day
</a>

<hr>

<div class="row">
    <div class="col-lg-8">
        <div class="row">
            <?php
            /** @var DayPlan $day */
            foreach ($this->days as $day) : ?>

                <div class="col-lg-6">
                    <?= $this->partial('planner/day', [
                        'day' => $day,
                        'dayNumber' => $counter,
                        'daysPlanQuery' => $this->daysPlanQuery
                    ]); ?>
                </div>


                <?php $counter++; ?>

            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card mt-3">
            <div class="card-header">
                Full Shopping List
            </div>
            <div class="table-responsive" style="max-height: 600px; overflow: auto;">
                <?= $this->partial('shopping/list', [
                    'items' => $this->shoppingList,
                    'list' => $this->list
                ]); ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function() {

        $('.add_to_meal_btn').on('click', function() {

            let id = $(this).data('id');

            // Show the form
            $('#hidden-add-form-' + id).show();
        });

        $('.submit-meal-to-planner').on('click', function() {

            let id = $(this).data('id');

            let form = $('#add_recipe_' + id);

            form.submit();
        });

    });

</script>