<?php

use Lib\DayPlan;

$counter = 1;
?>

<h2>Meal Planner for <?= $this->list->getName(); ?></h2>

<a class="btn btn-success btn-block" href="<?= $this->url('planner', [
    'list_id' => $this->list->getId(),
    'action' => 'add'
]); ?>">
    + Add a Day
</a>

<hr>

<div class="row">
    <div class="col-lg-8">
        <div class="row">
            <?php
            /** @var DayPlan $day */
            foreach ($this->days as $day) : ?>

                <div class="col-lg-6">
                    <?= $this->partial('planner/day', [
                        'day' => $day,
                        'dayNumber' => $counter,
                        'daysPlanQuery' => $this->daysPlanQuery
                    ]); ?>
                </div>


                <?php $counter++; ?>

            <?php endforeach; ?>
        </div>
    </div>

    <div class="col-lg-4">
        <div class="card mt-3">
            <div class="card-header">
                Full Shopping List
            </div>
            <div class="table-responsive" style="max-height: 600px; overflow: auto;">
                <?= $this->partial('shopping/list', [
                    'items' => $this->shoppingList,
                    'list' => $this->list
                ]); ?>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="col">
        <p>
            <i class="fa fa-burn"></i> Calories Per Person
        </p>
        <p>
            <i class="fa fa-users"></i> Number of servings
        </p>
    </div>
</div>

<script type="text/javascript">

    $(function() {

        $('.add_to_meal_btn').on('click', function() {

            let id = $(this).data('id');

            // Show the form
            $('#hidden-add-form-' + id).show();
        });

        $('.submit-meal-to-planner').on('click', function() {

            let id = $(this).data('id');

            let form = $('#add_recipe_' + id);

            form.submit();
        });

        $('.remove-day').on('click', function() {

            let dayPlanId = $(this).data('id');

            console.log(dayPlanId);
            $('#rm_dayplan_id').val(dayPlanId);

            $('#removeDayModal').modal('show')
        });

        $('.remove-recipe').on('click', function() {

            let dayRecipeId = $(this).data('id');
            let name = $(this).data('name');

            console.log(dayRecipeId,name);

            // Set values on modal
            $('#rm_recipe_id').val(dayRecipeId);
            $('#rm_recipe_name').html(name);

            // Show the modal
            $('#removeRecipeModal').modal('show');
        });

    });

</script>


<!-- Remove day Modal -->
<div class="modal fade" id="removeDayModal" tabindex="-1" role="dialog" aria-labelledby="removeDayModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeDayModal">Remove Day</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="<?= $this->url('planner', [
                'list_id' => $this->list->getId(),
                'action' => 'remove'
            ]); ?>">
                <div class="modal-body">
                    <p>Are you sure you want to remove this day? This action cannot be undone.</p>

                    <p>Marking the day as complete will also remove items from the list.</p>

                    <input type="hidden" name="rm_day_plan_id" id="rm_dayplan_id" value=""/>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Nooo keep it!</button>
                    <button type="submit" class="btn btn-danger">Delete it!</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Remove recipe Modal -->
<div class="modal fade" id="removeRecipeModal" tabindex="-1" role="dialog" aria-labelledby="removeRecipeModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="removeDayModal">Remove Recipe: <span id="rm_recipe_name"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="<?= $this->url('planner', [
                'list_id' => $this->list->getId(),
                'action' => 'removeRecipe'
            ]); ?>">
                <div class="modal-body">
                    <p>Are you sure you want to remove this recipe? This action cannot be undone.</p>

                    <p>Marking the recipe as complete will also remove items from the list.</p>

                    <input type="hidden" id="rm_recipe_id" name="rm_recipe_id" value="" />

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Nooo keep it!</button>
                    <button type="submit" class="btn btn-danger">Delete it!</button>
                </div>
            </form>
        </div>
    </div>
</div>