<?php

use Lib\Recipe;

/** @var Recipe $recipe */
$recipe = $this->recipe;

$this->headLink()->appendStylesheet("//cdn.quilljs.com/1.3.6/quill.snow.css");
$this->headScript()->appendFile('//cdn.quilljs.com/1.3.6/quill.min.js', 'text/javascript');
?>

<div class="row">
    <div class="col-lg-8">

        <div class="card mt-3">
            <div class="card-header">
                Recipe Details
            </div>
            <div class="card-body">
                <form id="recipeEditForm" action="<?= $this->url('recipe', ['action' => 'save']); ?>" method="POST">

                    <input type="hidden" name="id" value="<?= $recipe->getId(); ?>" />

                    <div class="form-group">
                        <label for="name">Recipe Name</label>
                        <input type="text" id="name" class="form-control" name="name" value="<?= $recipe->getName(); ?>"/>
                    </div>

                    <div class="form-group">
                        <label for="calories">Kcal per serving</label>
                        <input type="number" id="calories" class="form-control" name="calories" value="<?= $recipe->getCalories(); ?>"/>
                    </div>

                    <input type="hidden" id="instructionsHiddenField" name="instructions" value="" />

                    <label>Recipe Instructions</label>
                    <!-- Wysiwig Editor -->
                    <div id="editor" style="background-color: white; min-height: 600px">
                        <?= $recipe->getInstructions(); ?>
                    </div>
                    <!-- End wysiwig editor -->

                    <hr>

                    <button type="button" class="btn btn-primary" id="save-btn">Save Changes</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Items -->
    <div class="col-lg-4">
        <div class="card mt-3">
            <div class="card-header">
                Items

                <a href="<?= $this->url('recipe-item', ['recipe_id' => $recipe->getId()]); ?>"
                   class="btn text-info btn-sm float-right">
                    Edit
                </a>

            </div>

            <div class="table-responsive">
                <table class="table">
                    <?php foreach ($recipe->getRecipeItems() as $recipeItem) : ?>
                        <tr>
                            <td><?= $recipeItem->getItem()->getName(); ?></td>
                            <td>
                                <?= $recipeItem->getQuantity(); ?>
                                <?= $recipeItem->getItem()->getUnit(); ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <!-- /End items -->
</div>


<script>
    var quill = new Quill('#editor', {
        theme: 'snow'
    });

    $(function() {

        $('#save-btn').on('click', function() {

            let data = quill.root.innerHTML;
            console.log(data);

            // Set the hidden field value
            $('#instructionsHiddenField').val(data);

            // Submit form
            $('#recipeEditForm').submit();
        })

    })
</script>