<?php

use Lib\Recipe;

/** @var Recipe $recipe */
$recipe = $this->recipe;
?>


<h1>
    <?= $recipe->getName(); ?>
    <a class="btn btn-success" href="<?= $this->url('recipe', ['action' => 'edit', 'id' => $recipe->getId()]); ?>">
        Edit
    </a>
</h1>

<form id="servings-form">
    <div class="form-group row">
        <label for="servings" class="col-sm-2 col-form-label">Servings</label>
        <div class="col-sm-10">
            <select class="form-control" id="servings" name="servings">
                <?php for ($i = 1; $i < 10; $i++) : ?>
                    <option <?= $i == $this->servings ? 'selected':''; ?>><?= $i; ?></option>
                <?php endfor; ?>
            </select>
        </div>
    </div>
</form>

<div class="row">

    <!-- instructions -->
    <div class="col-lg-8">
        <div class="card mt-3">
            <div class="card-header">
                Instructions

                <a href="<?= $this->url('recipe', ['id' => $recipe->getId(), 'action' => 'print']); ?>"
                   class="btn btn-warning btn-sm float-right">
                    Print View
                </a>

            </div>
            <div class="card-body">
                <?= $this->recipe->getInstructions(); ?>
            </div>
        </div>
    </div>
    <!-- /End instructions -->

    <!-- Items -->
    <div class="col-lg-4">
        <div class="card mt-3">
            <div class="card-header">
                Items

                <a href="<?= $this->url('recipe-item', ['recipe_id' => $recipe->getId()]); ?>"
                   class="btn btn-info btn-sm float-right">
                    Edit
                </a>
            </div>

            <div class="table-responsive">
                <table class="table">
                    <?php foreach ($recipe->getRecipeItems() as $recipeItem) : ?>
                    <tr>
                        <td><?= $recipeItem->getItem()->getName(); ?></td>
                        <td>
                            <?= $recipeItem->getQuantity() * $this->servings; ?>
                            <?= $recipeItem->getItem()->getUnit(); ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
    <!-- /End items -->


</div>

<script type="text/javascript">
    $(function() {
        $('#servings').on('change', function() {
            $('#servings-form').submit();
        })
    })
</script>